<a href="https://colab.research.google.com/github/Alexandre77777/data_mining/blob/main/1.%20%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0/1.%20%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [69]:
import numpy as np 
np.__version__

'1.24.2'

2) Создать нулевой вектор размера 10

In [70]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3) Создать вектор заполненный 7-ами размера 7

In [71]:
np.full((1, 7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [72]:
np.linspace(10, 100, 46)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [73]:
arr = np.random.random_sample((1, 5))
arr

array([[0.1373145 , 0.93781875, 0.73834029, 0.20977037, 0.06102522]])

In [74]:
np.flip(arr)

array([[0.06102522, 0.20977037, 0.73834029, 0.93781875, 0.1373145 ]])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [75]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [76]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [79]:
arr = np.diag([1,2,3,4])
arr[arr == 0] = 7
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [80]:
np.full((4, 4), np.arange(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [118]:
arr = np.random.random_sample((10, 10))
arr

array([[0.34049538, 0.25066654, 0.71267726, 0.12056616, 0.06854358,
        0.32774522, 0.08890607, 0.48309172, 0.24771476, 0.10234557],
       [0.11754424, 0.89394913, 0.75117682, 0.4012797 , 0.62525405,
        0.60303896, 0.36343484, 0.30312114, 0.94652798, 0.89838239],
       [0.38165813, 0.53526958, 0.99494564, 0.87872068, 0.46785934,
        0.77739469, 0.08324068, 0.89070068, 0.70617368, 0.3984145 ],
       [0.50989741, 0.19840391, 0.51207311, 0.89816088, 0.24986164,
        0.74794108, 0.22121539, 0.94528724, 0.81700745, 0.94399768],
       [0.57001858, 0.01380479, 0.73884165, 0.54151688, 0.01474549,
        0.21030012, 0.51187795, 0.38302403, 0.80316502, 0.34926888],
       [0.83997271, 0.54948618, 0.93685748, 0.53714973, 0.09451149,
        0.28310182, 0.22840828, 0.14098176, 0.98088897, 0.82720352],
       [0.19815947, 0.75728072, 0.27718997, 0.17871303, 0.6468886 ,
        0.14880751, 0.06742951, 0.77016365, 0.30675062, 0.3152016 ],
       [0.45622958, 0.09258761, 0.7851645

In [119]:
arr - arr.mean(axis=1).reshape((10, 1))

array([[ 0.06622016, -0.02360869,  0.43840204, -0.15370906, -0.20573165,
         0.05346999, -0.18536915,  0.2088165 , -0.02656047, -0.17192966],
       [-0.47282668,  0.3035782 ,  0.16080589, -0.18909122,  0.03488313,
         0.01266803, -0.22693609, -0.28724979,  0.35615705,  0.30801147],
       [-0.22977963, -0.07616818,  0.38350788,  0.26728292, -0.14357842,
         0.16595693, -0.52819708,  0.27926292,  0.09473592, -0.21302326],
       [-0.09448717, -0.40598067, -0.09231147,  0.2937763 , -0.35452294,
         0.1435565 , -0.38316918,  0.34090266,  0.21262287,  0.3396131 ],
       [ 0.15636224, -0.39985155,  0.32518531,  0.12786054, -0.39891085,
        -0.20335622,  0.09822161, -0.03063231,  0.38950868, -0.06438745],
       [ 0.29811652,  0.00762999,  0.39500129, -0.00470646, -0.4473447 ,
        -0.25875438, -0.31344792, -0.40087443,  0.43903278,  0.28534732],
       [-0.168499  ,  0.39062226, -0.0894685 , -0.18794544,  0.28023013,
        -0.21785096, -0.29922896,  0.40350518

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [140]:
arr = np.random.random_sample((10, 10))
arr

array([[0.47608037, 0.442212  , 0.13327893, 0.14767231, 0.68478199,
        0.36713605, 0.1437763 , 0.13652446, 0.60429063, 0.13602353],
       [0.36175465, 0.76237732, 0.49124683, 0.35725371, 0.04272939,
        0.10257491, 0.41277986, 0.87175152, 0.965001  , 0.86971388],
       [0.97186043, 0.09102452, 0.09180217, 0.57560294, 0.09685529,
        0.78991871, 0.15513131, 0.1670856 , 0.91892228, 0.89558002],
       [0.64117379, 0.4952494 , 0.13062965, 0.40134255, 0.1095697 ,
        0.63899394, 0.30300004, 0.28096177, 0.65534796, 0.96488577],
       [0.85748299, 0.64464653, 0.10417762, 0.88393133, 0.25428796,
        0.26590072, 0.00800467, 0.93374553, 0.6555689 , 0.72150822],
       [0.87547112, 0.62597663, 0.36271656, 0.67944939, 0.90572536,
        0.68128627, 0.37287219, 0.29268634, 0.89047207, 0.31580302],
       [0.09420404, 0.83185139, 0.63698025, 0.26223978, 0.52011444,
        0.56863409, 0.65452172, 0.55722235, 0.59882948, 0.17679503],
       [0.23802922, 0.99684292, 0.1304496

In [141]:
arr - np.median(arr, axis=0) 

array([[ 0.05716286, -0.11840101, -0.02318691, -0.34080044,  0.34757722,
        -0.18543952, -0.19415981, -0.25688146, -0.05028362, -0.27797701],
       [-0.05716286,  0.2017643 ,  0.33478099, -0.13121904, -0.29447538,
        -0.45000065,  0.07484374,  0.47834559,  0.31042675,  0.45571334],
       [ 0.55294292, -0.46958849, -0.06466367,  0.0871302 , -0.24034947,
         0.23734315, -0.1828048 , -0.22632033,  0.26434803,  0.48157948],
       [ 0.22225628, -0.06536362, -0.02583619, -0.0871302 , -0.22763506,
         0.08641838, -0.03493608, -0.11244415,  0.00077371,  0.55088523],
       [ 0.43856549,  0.08403351, -0.05228822,  0.39545858, -0.08291681,
        -0.28667484, -0.32993145,  0.5403396 ,  0.00099465,  0.30750768],
       [ 0.45655362,  0.06536362,  0.20625072,  0.19097664,  0.5685206 ,
         0.12871071,  0.03493608, -0.10071958,  0.23589782, -0.09819752],
       [-0.32471347,  0.27123837,  0.48051441, -0.22623297,  0.18290968,
         0.01605852,  0.3165856 ,  0.16381643

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [142]:
arr = np.random.random_sample((5, 5))
arr

array([[0.77382657, 0.88333961, 0.03965026, 0.04437863, 0.95271039],
       [0.49876772, 0.71184116, 0.57131144, 0.26873323, 0.83595291],
       [0.68819248, 0.02081403, 0.87630121, 0.7690379 , 0.32856836],
       [0.96834684, 0.67130682, 0.60664612, 0.93668247, 0.28648201],
       [0.21387556, 0.31553699, 0.45373491, 0.23681683, 0.4036463 ]])

In [200]:
print(np.amax(arr, axis=1))
np.insert(arr, 1, np.amax(arr, axis=1), axis=1)

[0.95271039 0.83595291 0.87630121 0.96834684 0.45373491]


array([[0.77382657, 0.95271039, 0.88333961, 0.03965026, 0.04437863,
        0.95271039],
       [0.49876772, 0.83595291, 0.71184116, 0.57131144, 0.26873323,
        0.83595291],
       [0.68819248, 0.87630121, 0.02081403, 0.87630121, 0.7690379 ,
        0.32856836],
       [0.96834684, 0.96834684, 0.67130682, 0.60664612, 0.93668247,
        0.28648201],
       [0.21387556, 0.45373491, 0.31553699, 0.45373491, 0.23681683,
        0.4036463 ]])

In [201]:
print(np.amin(arr, axis=1))
np.insert(arr, 1, np.amin(arr, axis=1), axis=1)

[0.03965026 0.26873323 0.02081403 0.28648201 0.21387556]


array([[0.77382657, 0.03965026, 0.88333961, 0.03965026, 0.04437863,
        0.95271039],
       [0.49876772, 0.26873323, 0.71184116, 0.57131144, 0.26873323,
        0.83595291],
       [0.68819248, 0.02081403, 0.02081403, 0.87630121, 0.7690379 ,
        0.32856836],
       [0.96834684, 0.28648201, 0.67130682, 0.60664612, 0.93668247,
        0.28648201],
       [0.21387556, 0.21387556, 0.31553699, 0.45373491, 0.23681683,
        0.4036463 ]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [219]:
arr = np.linspace(1, 50, 50)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [214]:
arr[(arr % 2 == 0)].reshape(5, 5)

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.],
       [32., 34., 36., 38., 40.],
       [42., 44., 46., 48., 50.]])

In [220]:
arr[(~(arr % 2 == 0))].reshape(5, 5)

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [41., 43., 45., 47., 49.]])

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [235]:
x = np.zeros((8,8),dtype=int)
x[::2,1::2] = 1
x[1::2,::2] = 1
x


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])