<a href="https://colab.research.google.com/github/Alexandre77777/data_mining/blob/main/1.%20%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0/1.%20%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [1]:
import numpy as np 
np.__version__

'1.24.2'

2) Создать нулевой вектор размера 10

In [2]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
np.full((1, 7), 7)

array([[7, 7, 7, 7, 7, 7, 7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
np.linspace(10, 100, 46)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
arr = np.random.random_sample((1, 5))
arr

array([[0.08413758, 0.45115864, 0.38362244, 0.91710118, 0.74577669]])

In [6]:
np.flip(arr)

array([[0.74577669, 0.91710118, 0.38362244, 0.45115864, 0.08413758]])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [9]:
arr = np.diag([1,2,3,4])
arr[arr == 0] = 7
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
np.full((4, 4), np.arange(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [11]:
arr = np.random.random_sample((10, 10))
arr

array([[0.79174222, 0.43933428, 0.35126231, 0.22758935, 0.35763435,
        0.99162619, 0.6567147 , 0.71495875, 0.30125177, 0.09337852],
       [0.91030815, 0.5953688 , 0.79008132, 0.68429016, 0.31487561,
        0.26652696, 0.17509566, 0.38521791, 0.46041135, 0.14485647],
       [0.51619638, 0.42692569, 0.56028653, 0.0745097 , 0.74394765,
        0.47085102, 0.71804283, 0.48194858, 0.21598957, 0.77255357],
       [0.381686  , 0.10813795, 0.50991023, 0.11883928, 0.5714694 ,
        0.41078424, 0.55037675, 0.61687055, 0.67302484, 0.85807696],
       [0.71691463, 0.77733031, 0.98116213, 0.99254085, 0.38226878,
        0.38122071, 0.30396023, 0.72572021, 0.95496034, 0.58704115],
       [0.96478715, 0.96720251, 0.67406696, 0.11559876, 0.33004774,
        0.02718367, 0.43327801, 0.37466416, 0.43971995, 0.16757247],
       [0.66607341, 0.36604307, 0.79384732, 0.14893042, 0.6836775 ,
        0.11987679, 0.1500887 , 0.98592664, 0.52208733, 0.42877416],
       [0.4687007 , 0.1162336 , 0.0871547

In [12]:
arr - arr.mean(axis=1).reshape((10, 1))

array([[ 0.29919298, -0.05321497, -0.14128694, -0.26495989, -0.13491489,
         0.49907694,  0.16416545,  0.22240951, -0.19129747, -0.39917072],
       [ 0.43760491,  0.12266556,  0.31737808,  0.21158693, -0.15782763,
        -0.20617628, -0.29760758, -0.08748533, -0.01229189, -0.32784677],
       [ 0.01807122, -0.07119946,  0.06216138, -0.42361545,  0.24582249,
        -0.02727414,  0.21991768, -0.01617657, -0.28213558,  0.27442842],
       [-0.09823162, -0.37177967,  0.02999261, -0.36107834,  0.09155178,
        -0.06913338,  0.07045913,  0.13695293,  0.19310722,  0.37815934],
       [ 0.03660269,  0.09701837,  0.3008502 ,  0.31222892, -0.29804315,
        -0.29909123, -0.3763517 ,  0.04540828,  0.27464841, -0.09327079],
       [ 0.51537502,  0.51779037,  0.22465483, -0.33381338, -0.1193644 ,
        -0.42222847, -0.01613413, -0.07474797, -0.00969219, -0.28183967],
       [ 0.17954088, -0.12048946,  0.30731478, -0.33760212,  0.19714497,
        -0.36665575, -0.33644383,  0.4993941 

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [13]:
arr = np.random.random_sample((10, 10))
arr

array([[0.97234128, 0.11821123, 0.64134623, 0.167908  , 0.35203493,
        0.36741672, 0.3538394 , 0.16302294, 0.54686919, 0.63664051],
       [0.88223335, 0.59113779, 0.79636573, 0.57126942, 0.72027151,
        0.40996049, 0.07709071, 0.35038116, 0.09661489, 0.72632863],
       [0.38910867, 0.15941991, 0.56093662, 0.98359849, 0.41741144,
        0.83295812, 0.08558551, 0.99855862, 0.88691607, 0.59788241],
       [0.04601176, 0.63873621, 0.77624384, 0.83839625, 0.31911203,
        0.63249257, 0.11700578, 0.82215161, 0.61962935, 0.72051416],
       [0.01619765, 0.65001502, 0.62706057, 0.46902519, 0.46252385,
        0.50514911, 0.86417404, 0.04619937, 0.52085257, 0.89865019],
       [0.14643529, 0.54978806, 0.71880416, 0.04470632, 0.87405374,
        0.865867  , 0.49172006, 0.25152451, 0.97499348, 0.50033166],
       [0.19897501, 0.01526605, 0.37698372, 0.89591523, 0.90165282,
        0.42177423, 0.53839091, 0.37563959, 0.50323084, 0.35445094],
       [0.29727568, 0.71492522, 0.4741161

In [14]:
arr - np.median(arr, axis=0) 

array([[ 0.72421594, -0.36997528,  0.02995093, -0.47930567, -0.35606753,
        -0.18895138,  0.11070661, -0.34320229, -0.09500026,  0.0617583 ],
       [ 0.63410801,  0.10295129,  0.18497043, -0.07594424,  0.01216905,
        -0.14640761, -0.16604208, -0.15584407, -0.54525456,  0.15144642],
       [ 0.14098333, -0.32876659, -0.05045868,  0.33638482, -0.29069102,
         0.27659002, -0.15754728,  0.49233339,  0.24504662,  0.0230002 ],
       [-0.20211358,  0.1505497 ,  0.16484854,  0.19118258, -0.38899042,
         0.07612446, -0.12612702,  0.31592638, -0.0222401 ,  0.14563194],
       [-0.23192769,  0.16182851,  0.01566527, -0.17818848, -0.24557861,
        -0.05121899,  0.62104125, -0.46002585, -0.12101688,  0.32376798],
       [-0.10169005,  0.06160155,  0.10740885, -0.60250735,  0.16595128,
         0.30949889,  0.24858727, -0.25470072,  0.33312403, -0.07455055],
       [-0.04915034, -0.47292045, -0.23441158,  0.24870156,  0.19355037,
        -0.13459387,  0.29525812, -0.13058564

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [15]:
arr = np.random.random_sample((5, 5))
arr

array([[0.89081709, 0.2250783 , 0.10851619, 0.72774937, 0.51213664],
       [0.92607736, 0.54713472, 0.27851698, 0.96025992, 0.02160554],
       [0.7439193 , 0.95900652, 0.32925681, 0.81031931, 0.45960182],
       [0.52231734, 0.05122711, 0.32013796, 0.15992566, 0.80688759],
       [0.33483392, 0.79137828, 0.49509357, 0.52658845, 0.17510582]])

In [16]:
print(np.amax(arr, axis=1))
np.insert(arr, 1, np.amax(arr, axis=1), axis=1)

[0.89081709 0.96025992 0.95900652 0.80688759 0.79137828]


array([[0.89081709, 0.89081709, 0.2250783 , 0.10851619, 0.72774937,
        0.51213664],
       [0.92607736, 0.96025992, 0.54713472, 0.27851698, 0.96025992,
        0.02160554],
       [0.7439193 , 0.95900652, 0.95900652, 0.32925681, 0.81031931,
        0.45960182],
       [0.52231734, 0.80688759, 0.05122711, 0.32013796, 0.15992566,
        0.80688759],
       [0.33483392, 0.79137828, 0.79137828, 0.49509357, 0.52658845,
        0.17510582]])

In [17]:
print(np.amin(arr, axis=1))
np.insert(arr, 1, np.amin(arr, axis=1), axis=1)

[0.10851619 0.02160554 0.32925681 0.05122711 0.17510582]


array([[0.89081709, 0.10851619, 0.2250783 , 0.10851619, 0.72774937,
        0.51213664],
       [0.92607736, 0.02160554, 0.54713472, 0.27851698, 0.96025992,
        0.02160554],
       [0.7439193 , 0.32925681, 0.95900652, 0.32925681, 0.81031931,
        0.45960182],
       [0.52231734, 0.05122711, 0.05122711, 0.32013796, 0.15992566,
        0.80688759],
       [0.33483392, 0.17510582, 0.79137828, 0.49509357, 0.52658845,
        0.17510582]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [18]:
arr = np.linspace(1, 50, 50)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [19]:
arr[(arr % 2 == 0)].reshape(5, 5)

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.],
       [32., 34., 36., 38., 40.],
       [42., 44., 46., 48., 50.]])

In [20]:
arr[(~(arr % 2 == 0))].reshape(5, 5)

array([[ 1.,  3.,  5.,  7.,  9.],
       [11., 13., 15., 17., 19.],
       [21., 23., 25., 27., 29.],
       [31., 33., 35., 37., 39.],
       [41., 43., 45., 47., 49.]])

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [21]:
x = np.zeros((8,8),dtype=int)
x[::2,1::2] = 1
x[1::2,::2] = 1
x


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])